name: quant
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - python=3.8.5
  - pip=20.3
  - pytorch-cuda=11.7 
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
      - albumentations==0.4.3
      - diffusers==0.3.0
      - pudb==2019.2
      - invisible-watermark
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - test-tube>=0.7.5
      - streamlit>=0.73.1
      - torch-fidelity==0.3.0
      - torchmetrics==0.6.0
      - streamlit-drawable-canvas==0.8
      - einops==0.3.0
      - kornia==0.6.9
      - lmdb==1.3.0
      - natsort==8.3.1
      - omegaconf==2.1.1
      - opencv-python==4.1.2.30
      - opencv-python-headless==4.6.0.66
      - pandas==1.4.2
      - Pillow==9.0.1
      - pytorch-lightning==1.4.2
      - lightning-utilities==0.8.0
      - PyYAML==6.0
      - six==1.16.0
      - tqdm==4.64.0
      - transformers==4.22.2
      - git+https://github.com/CompVis/taming-transformers.git@master
      - git+https://github.com/openai/CLIP.git@main
      - -e .
